{% set name = "libsdformat" %}
{% set version = "9.0.0" %}
{% set major_version = version.split('.')[0] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://bitbucket.org/osrf/sdformat/get/sdformat{{ major_version }}_{{ version }}.tar.gz
    sha256: a0b4d809c5ebbaaf9f5eb344ba779fa0714047ed5676a4ccc63808fc6db94fcc

build:
  number: 0
  skip: true  # [osx or win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}              # [not win]
    - {{ compiler('c') }}                # [not win]
    - vs2017_win-64                      # [win64]
    - vs2017_win-32                      # [win32]
    - ninja                              # [not win]
    - ruby                               # [not win]
    - cmake
    - pkg-config
  host:
    - libignition-math6
    - urdfdom
    - boost-cpp >=1.71
    - tinyxml
    - console_bridge
  run:
    - libignition-math6
    - urdfdom
    - boost-cpp >=1.71
    - tinyxml
    - console_bridge

test:
  commands:
    - test -f ${PREFIX}/include/sdformat-{{ major_version + version.split('.')[1] }}/sdf/sdf.hh  # [not win]
    - test -f ${PREFIX}/lib/libsdformat{{ major_version }}.so  # [linux]
    - test -f ${PREFIX}/lib/cmake/sdformat{{ major_version }}/sdformat{{ major_version }}-targets.cmake  # [not win]
    - if exist %PREFIX%\\Library\\include\\sdformat-{{ major_version + '.' +version.split('.')[1] }}\\sdf\\sdf.hh (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\sdformat{{ major_version }}.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\sdformat{{ major_version }}.dll (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\lib\\cmake\\sdformat{{ major_version }}\\sdformat{{ major_version }}-targets.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://sdformat.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    Simulation Description Format (SDF) parser and description files.

extra:
  recipe-maintainers:
    - seanyen
    - j-rivero
    - conda-forge/ros-core
